### Get All Book
GET http://localhost:3000/api/library
X-API-Key: RAHASIA
Accept: application/json

### Create new book
POST http://localhost:3000/api/library
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "title" : "kosong",
  "years" : "0000",
  "publisher" : "kosong"
}

### Update book
PUT http://localhost:3000/api/library/10
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "title" : "Buku itu hijau",
  "years" : "1995",
  "publisher" : "Fulan1"
}

### Get book by Id
GET http://localhost:3000/api/library/10
X-API-Key: RAHASIA
Accept: application/json

### Delete book by id
DELETE http://localhost:3000/api/library/11
X-API-Key: RAHASIA
Accept: application/json